name: Sync Fork
on:
  schedule:
  - cron:  "0 0 8 * * *" # at 8AM
  workflow_dispatch: # on button click

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          token: ${{ secrets.TOKEN }}
